POST {{functionRoot}}/api/articleViewed/validateArticleViewForUser/purge HTTP/1.1
x-functions-key: {{functionsKey}}
####

POST {{functionRoot}}/api/articleViewValidated/writeArticleViewToStatisticsDb/purge HTTP/1.1
x-functions-key: {{functionsKey}}
####

POST {{functionRoot}}/api/articleViewStoredInDb/updateSearch/purge HTTP/1.1
x-functions-key: {{functionsKey}}
####

POST {{functionRoot}}/api/articleViewStoredInDb/updateCache/purge HTTP/1.1
x-functions-key: {{functionsKey}}
####